version: '3'

services:
  bot:
    build: .
    depends_on:
      - db
      - max
    restart: always

  max:
    image: quay.io/codait/max-toxic-comment-classifier
    restart: always

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toxbot
